### ISSUE TITLE
Top multilateral health aid providers

### ISSUE THREAD

**Issue by jm-rivera** [ONEcampaign/data_stories#10]

**Comment by jm-rivera** [comment]
@nupur-parikh over which period? I'll do over a rolling 5 year period

**Comment by jm-rivera** [comment]
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/68f6f81c-6c07-434f-8a7e-3670c321929e">
https://public.flourish.studio/visualisation/19578435/

**Comment by nupur-parikh** [comment]
This is perfect! thank you!
